[profile.default]
solc = "0.8.17"
optimizer = true
optimizer_runs = 200

src = 'contracts'
out = 'out'
libs = ['lib']
build_info = true

[fmt]
line_length = 120

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
optimism_goerli = "${OPTIMISM_GOERLI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
polygon_mumbai = "${POLYGON_MUMBAI_RPC_URL}"

[profile.local]
eth_rpc_url = "http://localhost:8545"

[profile.mainnet]
eth_rpc_url = "mainnet"

[profile.goerli]
eth_rpc_url = "goerli"

[profile.sepolia]
eth_rpc_url = "sepolia"

[profile.optimism]
eth_rpc_url = "optimism"

[profile.optimism_goerli]
eth_rpc_url = "optimism_goerli"

[profile.polygon]
eth_rpc_url = "polygon"

[profile.polygon_mumbai]
eth_rpc_url = "polygon_mumbai"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
